<?php
/**
 * Created by PhpStorm.
 * User: mirocow
 * Date: 06.08.15
 * Time: 1:02
 */

namespace app\modules\cabinet\components;

use app\components\Controller;
use app\models\Camera;
use app\models\Registrator;
use Yii;

/**
 * Site controller
 */
class CabinetController extends Controller
{

    public $layout = 'camera';
    public $activeCamera = null;
    public $activeLocation = null;
    public $activeCategory = null;
    public $cameras;
    public $jsonCameras;
    public $jsonRegistrators;
    public $registrators;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (\Yii::$app->request->isAjax) {
            return true;
        }

        if (!Yii::$app->user->isGuest) {
            list($cameras, $camerasArray) = Camera::getCameras();
            $this->cameras = $cameras;
            $this->jsonCameras = json_encode($camerasArray);

            list($registrators, $registratorArray) = Registrator::getRegistrators();
            $this->registrators = $registrators;
            $this->jsonRegistrators = json_encode($registratorArray);
        }

    }

    public function beforeAction($action)
    {
        if (!parent::beforeAction($action)) {
            return false;
        }

        if (!Yii::$app->user->isGuest) {
            if (Yii::$app->user->identity->role == 'USER') {
                return true;
            }
            if (Yii::$app->user->identity->role == 'ADDITIONAL_USER') {
                return true;
            }
        }

        return $this->redirect(['/site/login']);
    }

}